########################################################################################################################
# Customer parameters that are shared by multiple apps
########################################################################################################################

global:

  ############################################################
  # Secrets
  ############################################################
  # Expected format for each secret:
  # NAMESPACE:
  #   KEY1: VALUE1
  #   KEY2: VALUE2
  # Note: NAMESPACE need to match exactly,
  #   but secret keys should follow Helm's camelCase guidance
  ############################################################
  sealedSecrets: false
  secrets:
    ping-cloud:
      ###### Shared Secrets ######

      # License key that is used to enable and point to a NewRelic instance
      newrelicLicenseKey: dW51c2VkCg==
      # Profile Repo SSH Id key secret
      sshIdKeyBase64: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUE3OHNnb3F6R2RmWDFDdWlSbXBscFFzQ1NacGZvVkxNZWlKSkFmMjVFSnRTYjFMVXRYVDkxCmwyV29od2paRFBkUmFjYTBEOTEzZUpqbnJBK0srZmtneGRIMTJtbXZ1V3FSYnlheFdkSU0zL0pGWFNuVUw2N3MwaCtKUzEKTEl3M0gxTDB4T1ZxS0dHQVFUaG5ncWVQdnJxcHZVZlB2dVdiaXM1NlJVTW5EWS9pRlRQakNKOEV0aHk0VUtFVUtsYzh0Qwp1UUg2RUcyOEQxRE5KNGI3ek05dkxZZ0F5NW5JN2N3Zk9selB6VVpTbWlXYklLc1RKYnRKVlNsZWFkTjF1SUZnQU1TSWZjCmx4NTlZOXY5aVNhbkcwNXV6TGVEZHF1SUg0RDJhMmMxNnpiNVhyNlB4SjhjUmZiSW1QeVA4OU9FOURkdWN4c1RkYllMd2UKbGtwWTVabld3blh0M09XSURrUURRc2dlZTR2QVpQaVorT1RCay9ZbHRadk82SFphSFRoc2hhM2xGOXhFNzM2SjFLYlJBdApQOTM5M09UVVNweGdFbWk3RVI1TVVYKzRremZaVDFiYWhWUU5KbVFWQ1p3N25vdUJDNExOMHk1VUM3ZVJtNkhBcGpUc1duCjhjUlFtRHpkYjRVTkt2WEJKbkd1MGtEdWVjaVJYMHE4QkRPSXFMZ3JBQUFGa0ZNWHZ4aFRGNzhZQUFBQUIzTnphQzF5YzIKRUFBQUdCQU8vTElLS3N4blgxOVFyb2tacVphVUxBa21hWDZGU3pIb2lTUUg5dVJDYlVtOVMxTFYwL2RaZGxxSWNJMlF6MwpVV25HdEEvZGQzaVk1NndQaXZuNUlNWFI5ZHBwcjdscWtXOG1zVm5TRE4veVJWMHAxQyt1N05JZmlVdFN5TU54OVM5TVRsCmFpaGhnRUU0WjRLbmo3NjZxYjFIejc3bG00ck9la1ZESncyUDRoVXo0d2lmQkxZY3VGQ2hGQ3BYUExRcmtCK2hCdHZBOVEKelNlRys4elBieTJJQU11WnlPM01IenBjejgxR1Vwb2xteUNyRXlXN1NWVXBYbW5UZGJpQllBREVpSDNKY2VmV1BiL1lrbQpweHRPYnN5M2czYXJpQitBOW10bk5lczIrVjYrajhTZkhFWDJ5Smo4ai9QVGhQUTNibk1iRTNXMkM4SHBaS1dPV1oxc0oxCjdkemxpQTVFQTBMSUhudUx3R1Q0bWZqa3daUDJKYldienVoMldoMDRiSVd0NVJmY1JPOStpZFNtMFFMVC9kL2R6azFFcWMKWUJKb3V4RWVURkYvdUpNMzJVOVcyb1ZVRFNaa0ZRbWNPNTZMZ1F1Q3pkTXVWQXUza1p1aHdLWTA3RnAvSEVVSmc4M1crRgpEU3Ixd1NaeHJ0SkE3bm5Ja1Y5S3ZBUXppS2k0S3dBQUFBTUJBQUVBQUFHQVRodzQwVVMra1FaQmdBQXFEZFlUTjY5TEFTCmhTZ2VTbStZM0tmTGdLY3l1bVp5OXRTNGEwWTFDMkNPYVU3V2hTbU1ZbE9WWEc2UDNGMllKbW51N01BaVJXbFlML3ZzSTgKQlp6eEFIVXZ4SE5DclFwSEdCRS9DMk5DY2NyUm92aW9DWFF0d0lMSWMySkFpZmp5dk40eThpdzRsMDNwWWtpSjZoclpZbQpUb0NrQUl3YVZHQ1lSRW91ci9VSWdKSlNMODVROER5ZjQwMkRoVjI1NVl2MnFDcUs0NHRCbXdIZVh6OWlydGRjeUdjN2YwClJEdjF6TUNwTHBoL0xMRzVFeFR3ODJMRmhzb2VOeDAvUWY4ZGNna053RXY2NSt3d0ExVlVNWWJhL1lZODNNTE53bFJKL3QKRm1SQU9LeUdHcWdlNjVndFZYTVpCeStBeTB1c2VvSXNzTzdGa09SdkN1YjVPZXZZc3ZDRWk3MXp2WE5tazNRRzZtZ0xaaAp3UGVtYXBZNFZzeFhuQXZKTzZPSkErUGIyQ1Zwd0dyc0hKcEN0bnEvdkcyc1FxZmtNWGRjenlmcmUvVCtGRUQxbnNIdFBICkpEY1BOajl1SzFzaWoxajRSdi9GMnU5M1hnMG9wNE5CdytzUUhkV2hDYzdLd2thejBKb09jRW1GeHRwb2pTbkczaEFBQUEKd0h0S2dUQTY1WlRDbjNSazM3bHNRUnQvekE0OUM0b3JOVy93MDRjU29iTWE0SVI4M2Rsd05Nb2ROOHdHUjMvUWV6WDhQRApvd0FxQmRVcmV6VEgvUWUwOGEyVWhxa1NQZ3hJbmpReVVtQWpJZEZqc2psWlk1a21YOGZWL0lsUHI3dTNOcjhnMDJFc0x0CndKOHFZbldCRkVsNFQ0VjRNQWN4SmFIeVhoSGlrNm9ldER1VmFKL09xTXhPYzdNeDhXU1Bwc0JmTmtQVWFpUVBlTUxKcXMKMmRLMTkvVkovL1dvcW9pNWRsa2N2S3JQL1lLbGRjYmlPQUJDQmtvTFRlYS9laEpRQUFBTUVBK2lFVTlpMXhDMzVvZENaZgp6alNzNEpwK1RCcy8wQmVDdSt0VmV0Z2s5TG5FRGdML3FZRDAxSjBKQTIraWRkSlhpY21raWpSMHNFUXBsUFhKbndtTCtYClAvNWhSOHUyZE16UnV5UkUxRG9DYVhQOEJHQnh6TGxSdFZzWUlFT0VyQmM1V2hCaWZoTDF5bTBwMWY0dnVtRVBrdGJuRWEKTi9GZDF4eGVkeHYwNmdwQzRLS1hUREJKOEV4eHkwRUgyYzZSaTJrK1dhU2JWSXpIc3JnY09FSGJPRkJlblZmN00wemJidwpRcStFWjJyS0tFcFJlL0tlRVZEb0VuMFlnL2dzYXZBQUFBd1FEMWEvRkgwVWhkWVg1OEJMVXBxY1p3QlNIUHNENFp0YmxuCnIvNE82VmNLdzlxcHIrV1A3dTczS2kyeXFCUytvc1kwbVo0bFZqYWs5ZHh6eG1YK24yM2JML0pIL1VEYURubUhELzdQTk4KZ3h3ZDFJTE04V3g0Vm1ubmlsbVBjNmZuSVMycVc1c1VHbkllRUFEMHdMdTFraEdiaTNPYVNPUEdvc0dRaWRKVzd2bHFnQwpQbzQrUGxEQmYwUFptUXNsV3orNlhPQk5waGdDc0U5aTM2NFh6cm96RlphK1Y4VlJnV2tGSmtzbWtzK0ZXME5xSEFnTlJUCkg1WVJVbFRmbmtSVVVBQUFBV1lXMWxhSEp2ZEhKaFFHMWhZeTFHVmtjek1qUlNOUUVDQXdRRgotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
      # Used as default password for PD admins (used by PD and datasync)
      rootUserPassword: MkZlZGVyYXRlTTByZQ==
      # Default Admin User Password for PingFederate
      pfAdminUserPassword: MkZlZGVyYXRlTTByZQ==
      # Used as default password for PF admin users interacting with PD
      pfLdapPassword: MkZlZGVyYXRlTTByZQ==
      # Password used to authenticate to PD keystore (used by PD and certmanager)
      acmeCertKeystorePassword: MkZlZGVyYXRlTTByZQ==
      # Secret synced between DelegatedAdmin and PingDirectory
      daOauthTokenValidatorSecret: MkZlZGVyYXRlTTByZQ==
      
      ###### PingDirectory Secrets #####

      # Mounted as a file on PD container and used for dsreplication commands
      adminUserPassword: MkZlZGVyYXRlTTByZQ==
      # Mounted as a file on PD container and used for encryption/decryption of database
      encryptionPassword: MkZlZGVyYXRlTTByZQ==
      # Backup encryption password
      oldEncryptionPasswords: MkZlZGVyYXRlTTByZQ==
      # An alternative to encryption password in .pin file format
      encryptionSettingsPin: MkZlZGVyYXRlTTByZQ==
      # Client ID to be used with P14C
      p14cClientId: ODkwNzM2NTQtNGVkMy00YTViLWI4OWMtZmY2YjVlMWI3ZDFi
      # Client secret to be used with P14C
      p14cClientSecret: UXA4aTAudHg4U3dVSWphdnlYWn5KYTZLQlA5SzN+azljTUYuUWF4UTZYclBvdHpmOU5DbFk2bHRLLjBJUU42MA==
      # Environment ID to be tused with P14C
      p14cEnvironmentId: YzNlMzczNTctNTA2Mi00MWJjLTk5NzItYTdlYTlkMTRhNWEy
      # The DManager password for new P1AS clients,  who will inherit the default permissions associated with PingDirectory.
      dmanagerPassword: MkZlZGVyYXRlTTByZQ==
      # Cert used for inter-PD communication
      adsCrt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2akNDQWFZQ0NRQ3NMaEptdEYwQ3VEQU5CZ2txaGtpRzl3MEJBUXNGQURBZ01SNHdIQVlEVlFRRERCVnMKYjJOaGJHaHZjM1F1Ykc5allXeGtiMjFoYVc0d0lCY05NakF3TmpNd01UZ3hOekkwV2hnUE1qRXlNREEyTURZeApPREUzTWpSYU1DQXhIakFjQmdOVkJBTU1GV3h2WTJGc2FHOXpkQzVzYjJOaGJHUnZiV0ZwYmpDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtmalRHZVgweHhubG5LbXBodFB1Z21jRjNXRHREZmsKOUgyWGh4aXpsTzliNzhPWlk3ZGRxZXVpRktBU3ZZZEtzSE80cUVLMXhtMitvTHZaa2RIandFYlc5dVJYQ2Zucgo3cUpRaHpiemZpemtFOXE2MVBHazJTNGNlcytyUlBDZVlFSEUrd1J5bUdnMnNabXgrdVNLb1RvQk5lMnNnQ2lWCkw0YmpBZ3NKdkdxUzI2T0ZleTF6WTVRYXRmUkI0QlFKSis1eFJ3Z3BCSXdJOExRN3ozS0pkQlVyTll3TDlUemYKSVc2UjcxMHlORVhWWkxqa0pwemJTeGtub3kxQlc3SFJwYmxxNFZaWEFEWDNSYlpuV2xKRWhubkRBVGxPcWtregp5cHBUSnhvaEtkK0pZYXRFRUxWNC9DajkyR3UwcEJtSXorazkrWnJob3J1RTBkSHM2T0tlYStVQ0F3RUFBVEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVNVcUU1RUw1ZEttNDJWcmFEclpRM0prNXlTUUNtZE1HNGFoYmFndVUKNDk1aEV5NDlhNVhDL3NoS0hCUnJaVy95RTJiS1dTOTBKdzA2aVpUWkk0a3JXZnk5NUtxVlJhWkNYUHc4K0lWdwpLMjJZSTJ1MWVUNlpWYkpuL1dJL2VuMDBwNk1mRjhFTmF3STZTc081dzlVUnRhSFpRK2lhc1BSUERqeVljUC93CnNpbWlBeTB2a2hZSUM5Qmw1K0QxV3FwWm1PRnMvdW5EZC8xUFRxSXF5cHZINUcyYjBvUmdLTTUzQlBIZFBKajAKcEpObFBTblJFNThVNkM5RG5BcSt2cFlJZFE1UWdtQWVaMVA0T2E0cGdHY0NHNlBVYVRoalUxeFhFL01CQWFFRgpwV0pYT2pqWHUwdVpFbXE0bHFJakZEcmZDSkVISkliRmtzMUJjZVVQK3BkU2F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      # Key used for inter-PD communication
      adsKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQ240MHhubDlNY1o1WnkKcHFZYlQ3b0puQmQxZzdRMzVQUjlsNGNZczVUdlcrL0RtV08zWGFucm9oU2dFcjJIU3JCenVLaEN0Y1p0dnFDNwoyWkhSNDhCRzF2YmtWd241Nis2aVVJYzI4MzRzNUJQYXV0VHhwTmt1SEhyUHEwVHdubUJCeFBzRWNwaG9OckdaCnNmcmtpcUU2QVRYdHJJQW9sUytHNHdJTENieHFrdHVqaFhzdGMyT1VHclgwUWVBVUNTZnVjVWNJS1FTTUNQQzAKTzg5eWlYUVZLeldNQy9VODN5RnVrZTlkTWpSRjFXUzQ1Q2FjMjBzWko2TXRRVnV4MGFXNWF1RldWd0ExOTBXMgpaMXBTUklaNXd3RTVUcXBKTThxYVV5Y2FJU25maVdHclJCQzFlUHdvL2RocnRLUVppTS9wUGZtYTRhSzdoTkhSCjdPamlubXZsQWdNQkFBRUNnZ0VCQUp4NXMwcVNMUWM2WFBTNjhmSmVtb3crV1hjRHE4SzB1Rk1lR2FJaUxsdngKR2tUNkFBQjFZZHZta3NhbThOTGFBQis3S2NnVFY4QU5mZzNYT0p1aFpDSWlWTFo1a1NqSWh2L3RnampyTk54dQpMenNjQzBDMVhsNGwyU2tZL2dZdDlwVVdITWNHYjVvaDcrSEtDb2RiMWUwVUY4bFBqNXREZ0twOWhmZjN1UTZ5CkUxRWl0WHJ6Yk9qNzU4QllXRXc1cXdPS2orWGZIS3FJcDc2dGp6NEM3dlJPUDF5OFBaN1BuYUV2V3VSVXNIdkUKVTB1aXJVc3doYjZJSE10UUxGM21EUEo5Y2lEWmI3NWFjbmtEZTRHc1ZQSHJ5bDNKMGpnZnpNS2dtT1RKZWVFTAprcEsvUHI1eVNMTEZnNjloYVlDU0hLVEt6ME9OUjVXc3dmdjl2WnBjQXNFQ2dZRUEwNEZ3cjcwMitVK3R5d1NNCmlZM0JvNFZEeXVLVXlsQThxUE1COGlCK0cxaXdJenBWSk1hakNZR2dLcUhMZUpGWjM0RGNCUkNiVnZ0RlhpU0UKSW5NQ0taYStlOTh1UXVjcGJzV2tBM3oxT0hMN1dscFp3OTMwZlBkVkNVYW1KZEhYUTJjQ01udDFMRmwyWmVQTwpyVG1rMmdXMHMzYTNHMWRvNjFJM3NZamNHc2tDZ1lFQXl6VFhKa3RUVXZ6L1hqVDhrMDBoUFREWjZzR1RUOEt2CjBERzU0c1ZNYWRTb2hXYi9oUkZ6WHo4Q21YMWQyRDZSS3NaK3pVNjcydCtqY0pDdmd2L3phRWpBZ3M5cXVMTFIKd2s1S29qbmZGT2FobEN3TDladVA0c01kcHZwU2JUS0RPTGdzMXQ1TkcreTlkZEFiSzdMNDFkMTRSbEw4bHZ4OApzdnk4eitvR3VqMENnWUJaU1NGYTd0T1FONVMwU1gxU2JDYzhjbnVGNEZUVGV6L0FTcVdkb3gzWlNYMUJ3ZFJECnJCOFRXa2RVOSt3L1A0empEekRTYW9wSkU5WGF3aXVOcDJOWVR5eW1lamE3UTM1NEpyTHdUZ1h2Q0lzWFAyRDUKa0c4dmVmSEo4cXNjK0JLWmY1aXIydlpCL0pwQXRRU0FsLzhCa3JzUHI2UG94T09qdzVlRE9MVkNFUUtCZ1FDegptNExISURFSDJ3TEQrOFY3Vk9NYU9NR0VFNURuSU1kUkY0S2JnNVBrdnNndEVUcXNIUjZDZ3lrRERhSVM3a3BWCktwa05VcGdML3p0dzFSR3NraHBNaEhGVHJZMUFyeDFqeHR1RXcrMy9oVkl2cXpidTRZNnQrWk9OOFJkRjJTM08KeGtzcnA5VXo1MjRXWWRpQ0tYQnpaNHRWYlNoQk0rM3NMaU9kQ2Ria2FRS0JnUUN4b3ZCYXpjR2VEMXFsRjREUgo0eXZpYUpCeUNPM3ludEQwMXAvUGRCTDJNWHA2bjAzWVZEa1BHUytqamZtamt3QVV0ek9RU2pZUGViWWtlb21yClZMZ2N1YkN1VGZsNmNQbnRxUHZxM1pVT2ZqUlB1REI4MjZ0Rm82RDZEUHYwQ043WnE4Y3ZpK3h0RExqWjRDbG8KdFd3a3JWZ3JTeEljd1dyaTBMcXNXTExmV2c9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      # Optional license key for PingDirectory
      # pingDirectoryLicense: ""
      # Optional certificate(s) to add to the PD truststore. Name must have the prefix "pdTruststore" Ex below:
      # More info here: https://confluence.pingidentity.com/display/proserv/Enabling+X.509+Authentication+with+PingDirectory
      # pdTruststoreCertOne: certOneData
      # pdTruststoreCertTwo: certTwoData

  ########################################################
  # Multi-region parameters
  ########################################################
  isMultiCluster: false

  # primaryRegion is the primary AWS region name
  # the primary region should have the same value for region and primaryRegion
  primaryRegion: "us-west-2"

  # primaryDnsZone is the primary dns zone for customer for region
  primaryDnsZone: "amehrotra-primary.ping-demo.com"

  # primaryTenantDomain is the primary domain suffix for customer for region
  # the primary region should have the same value for tenantDomain and primaryTenantDomain
  primaryTenantDomain: "amehrotra-primary.ping-demo.com"

  # secondaryTenantDomains is an optional comma-separated list of the tenant domain suffixes of secondary regions used
  # for PingFederate adaptive clustering using the JGroups DNS_PING discovery protocol:
  #
  #   - Do NOT include the primary tenant domain in the list
  #   - Do NOT include the CDE prefix in the domain name
  #
  # For example, if the primary domain is "tuna.us1.ping-preview.cloud", then set it
  # to "tuna.eu1.ping-preview.cloud,tuna.au1.ping-preview.cloud" to specify secondary
  # domains in regions eu1 and au1.
  #
  # NOTES:
  #   - Only used in multi-cluster environments. If provided, PF will be configured with DNS_PING.
  #   - It is recommended that SECONDARY_TENANT_DOMAINS be set apriori, even before the
  #     secondary regions are created to avoid pod rollouts. DNS_PING will simply ignore
  #     unreachable domains. If it is not set beforehand, then all servers in the PF
  #     cluster (admin and engines) must be re-rolled to pick up the change.
  secondaryTenantDomains: ""

  # globalTenantDomain is the region-independent URL used for DNS failover/routing
  globalTenantDomain: "global.amehrotra-primary.ping-demo.com"

  ########################################################
  # S3 buckets
  ########################################################
  # pingArtifactRepoUrl is the ping-hosted common artifacts URL
  pingArtifactRepoUrl: "https://ping-artifacts.s3-us-west-2.amazonaws.com"

  # logArchiveUrl is the customer-specific log URL for region
  logArchiveUrl: "ssm://amehrotra-primary/pcpt/service/storage/logs/uri"

  # backupUrl is the customer-specific backup URL for region
  backupUrl: "ssm://amehrotra-primary/pcpt/service/storage/backup/uri"

  ########################################################
  # Miscellaneous ping-cloud variables
  ########################################################
  # pingCloudNamespace is the namespace where Ping apps are deployed
  pingCloudNamespace: "ping-cloud"

  # k8sGitBranch is the ping-cloud-base git branch for base Kubernetes manifests
  k8sGitBranch: "PDO-5995"

  # ecrRegistryName is the name of the Docker image registry
  ecrRegistryName: "public.ecr.aws/r2h3l6e4/dev"

  # clusterName is the eks cluster name
  clusterName: "amehrotra-primary"

  # serverProfileUrl is the git URL for the profile repo
  serverProfileUrl: "ssh://APKA2IO25QZR5RKID5ET@git-codecommit.us-west-2.amazonaws.com/v1/repos/amehrotra-primary-profile-repo"

  # serverProfileBranch is the git branch for the profile repo
  serverProfileBranch: "dev"

  # Placed in ~/.ssh/known_hosts file to avoid ssh prompts when cloning the cluster state repo
  sshKnownHosts: "|1|Kgg3l3YylS1HFpeszX6YddHmXJc=|aLUcY9xzWv1rdjyn+XOuK6ED6/s= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqyQh/szYdP7ykDdwp8pWMgrFmuXU4mEf27Wzz6QcR/ZJsIRVCdslVjmt9RA1ljanAVPI8zjp/oI6NPICh8l638vRLt8lFbNMfMMfkzxiIXs0mLAuQ2XSbRglPDF4mAQ7C+oD/B01XXKWU4Vack37i0R9RMtkl3spFB8Hq7HJi4/wy87U7FMHfjHWYXr3GAOg1PfRyTAyHij0XXuBhxzz1vMoiI5DkgH8CKuKf+AmW5KHxKX3zPCoKe7nDw3/Re4ghYhc34ldOSZlQin/dIyT/GQy0ayRWGXc0KB2ijrDCxd4N4INBhdqCRDPwkxwqVRUToBFw6Q1zBdlVlK5ViFEV"

  # The image pull policy for all images
  imagePullPolicy: "Always"

  # Boolean determining if this is an isolated microservice or a full PCB deploy
  isMicroserviceDeploy: false

  ########################################################
  # Environment-specific variables
  ########################################################
  # environmentType is used by server profile hooks
  environmentType: "dev"

  # env is used by Kubernetes manifests
  env: "dev"

  isBelugaEnv: true

  ########################################################
  # DevOps License environment variables
  ########################################################
  pingIdentityDevopsUser: "amehrotra@pingidentity.com"
  pingIdentityDevopsKey: "e94a63f3-6d8c-1c0f-848f-2aa79ec482c0"

  ########################################################
  # Shared Application Variables
  ########################################################
  # Define the contents for your descriptor.json file here, in yaml. An example is provided below for syntax.  
  # Also see the descriptor.json.readme file in p1as-pingdirectory/deploy/templates/config directory of the 
  # p1as-pingdirectory repo for more info
  # descriptorFile: |-
  #   us-west-2:
  #     hostname: abc
  #     replicas: 1
  #   us-east-2:
  #     hostname: def
  #     replicas: 2
  descriptorFile: ""
  # PingDirectory base DN
  userBaseDn: "dc=example,dc=com"
  # Alternate Base DNs
  userBaseDn_2: ""
  userBaseDn_3: ""
  userBaseDn_4: ""
  userBaseDn_5: ""
  # The prefix of a SSM Param / Secret path that contains TLS config
  customerTlsSsmPathPrefix: "/amehrotra-primary/pcpt/customer/tls"

  ########################################################
  # Public Hostnames
  ########################################################
  pdClusterPublicHostname: "pingdirectory-cluster.amehrotra-primary.ping-demo.com"
  selfServicePublicHostname: "self-service-api.amehrotra-primary.ping-demo.com"


  #### FEATURE FLAGS ##################################################################################################
  # Most are disabled by default
  # Please follow runbook instructions for the given feature flag to enable/disable

  # !!! Provisioning for PingFederate is not yet available for multi-region customers !!!
  # Runbook: https://confluence.pingidentity.com/display/PingCloud/How+to+Enable+and+Configure+PingFederate+Provisioning
  pfProvisioningEnabled: false

  radiusProxyEnabled: false

  external_ingress_enabled: 

  # Runbook: https://pingidentity.atlassian.net/wiki/spaces/PDA/pages/427688292/How+to+Enable+and+Disable+Healthchecks+-+1.19.0
  healthchecksEnabled: false
  #####################################################################################################################

  ########################################################
  # App Specific Variables
  ########################################################

  # pingcloud-p14c-bootstrap application settings
  p14cIntegration:
    image: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration/dev:v2.1-release-branch-latest
