{{- if .Values.cloudwatch.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudwatch-agent-role-binding{{ include "cloudwatch.non-namespaced.name" . }}
subjects:
  - kind: ServiceAccount
    name: cloudwatch-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cloudwatch-agent-role{{ include "cloudwatch.non-namespaced.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
