kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../base/custom-resources
  - custom-resources

helmCharts:
  - name: p1as-cloudwatch
    additionalValuesFiles:
      - ../../values-files/base/values.yaml   # base values.yaml
      - ../../values-files/${REGION_NICK_NAME}/values.yaml   # regional values.yaml
      - values.yaml   # app specific values.yaml
    version: v2.1-release-branch-latest
    repo: oci://${ECR_REGISTRY_NAME}/dev
    namespace: amazon-cloudwatch
    
### This field is used to trigger a resync of the helm chart ###
configMapGenerator:
  - name: last-update-reason
    literals:
      - UPDATE_REASON=""
  ### This is needed for the empty custom-patches.yaml file to work ###
  - name: o11y-custom-placeholder
  ### This is needed for the empty custom-patches.yaml file to work in base folder ###
  - name: o11y-custom-placeholder-base      

patchesStrategicMerge:
  ### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
  - custom-patches.yaml
  - ../base/custom-patches.yaml