kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- cluster-tools
- ping-cloud
- sealed-secrets.yaml

### PSO/GSO teams should only add new custom resources in this directory. Otherwise, CSR auto-updates will break. ###
- custom-resources

patchesStrategicMerge:

### Reference to all secrets ###
- secrets.yaml

### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
- custom-patches.yaml

patches:
  # TEMP patch until we can fix Karpenter upgrades for CDEs NOT using Karpenter
  - patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: nodepools.karpenter.sh
      $patch: delete
  - patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: nodeclaims.karpenter.sh
      $patch: delete
  - patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: ec2nodeclasses.karpenter.k8s.aws
      $patch: delete
  - patch: |-
      apiVersion: karpenter.k8s.aws/v1beta1
      kind: EC2NodeClass
      metadata:
        name: default
      $patch: delete
  - patch: |-
      apiVersion: karpenter.k8s.aws/v1beta1
      kind: EC2NodeClass
      metadata:
        name: pd-only
      $patch: delete
  - patch: |-
      apiVersion: karpenter.k8s.aws/v1beta1
      kind: EC2NodeClass
      metadata:
        name: pgo-only
      $patch: delete
  - patch: |-
      apiVersion: karpenter.sh/v1beta1
      kind: NodePool
      metadata:
        name: default
      $patch: delete
  - patch: |-
      apiVersion: karpenter.sh/v1beta1
      kind: NodePool
      metadata:
        name: pd-only
      $patch: delete
  - patch: |-
      apiVersion: karpenter.sh/v1beta1
      kind: NodePool
      metadata:
        name: pgo-only
      $patch: delete
  # END TEMP patch