{
 "title": "PingAccess Per-Server Dashboard",
 "description": "PingAccess Metrics by Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "JVM GC CPU, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{k8s_cluster_name=~\"$cluster_name\", cluster=\"pingaccess-cluster\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Old Gen (Tenured) Collected, %",
   "type": "timeseries",
   "description": "JVM GC Old Gen (Tenured) Collected, Formula: GC Old Gen (Tenured) Collection Usage Used / GC Old Gen (Tenured) Collection Usage Max * 100 ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_PS_Old_Gen_CollectionUsage_used{k8s_cluster_name=~\"$cluster_name\", cluster=\"pingaccess-cluster\"} or java_lang_Tenured_Gen_CollectionUsage_used{k8s_cluster_name=~\"$cluster_name\", cluster=\"pingaccess-cluster\"})/(java_lang_PS_Old_Gen_CollectionUsage_max{k8s_cluster_name=~\"$cluster_name\", cluster=\"pingaccess-cluster\"} or java_lang_Tenured_Gen_CollectionUsage_max{k8s_cluster_name=~\"$cluster_name\", cluster=\"pingaccess-cluster\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time 90 Percentile",
   "type": "timeseries",
   "description": "This panel shows the 90th percentile of response time across all PingAccess servers in the selected cluster(s). This metric is derived from the `.response.time.statistics.90.percentile` metric collected from each PingAccess instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_time_statistics_90_percentile{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time Mean",
   "type": "timeseries",
   "description": "This panel shows the mean response time across all PingAccess servers in the selected cluster(s).This metric is derived from the `.response.time.statistics.mean` metric collected from each PingAccess instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_time_statistics_mean{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Concurrency 90 Percentile",
   "type": "timeseries",
   "description": "This panel shows the 90th percentile of response concurrency across all PingAccess servers in the selected cluster(s).This metric is derived from the `.response.concurrency.statistics.90.percentile` metric collected from each PingAccess instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_concurrency_statistics_90_percentile{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Concurrency Mean",
   "type": "timeseries",
   "description": "This panel shows the mean of response concurrency across all PingAccess servers in the selected cluster(s).This metric is derived from the `.response.concurrency.statistics.mean` metric collected from each PingAccess instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_concurrency_statistics_mean{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "This panel shows the total number of requests across all PingAccess servers in the selected cluster(s).This metric is derived from the `.response.statistics.count` metric collected from each PingAccess instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingaccess_response_statistics_count{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}