apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              cpu: "3"
              memory: 10Gi
            requests:
              cpu: "3"
              memory: 8Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xms6g -Xmx6g -XX:MaxDirectMemorySize=2g'
            - name: PIPELINE_WORKERS
              value: "12"
            - name: PIPELINE_BATCH_SIZE
              value: "500"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic-s3
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              cpu: "2"
              memory: 6Gi
            requests:
              cpu: "1500m"
              memory: 4Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xms3g -Xmx3g -XX:MaxDirectMemorySize=1g'
            - name: PIPELINE_WORKERS
              value: "16"
            - name: PIPELINE_BATCH_SIZE
              value: "1000"
