### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###

### Always leave in at least this customization. Otherwise, kustomize will complain about an empty patch file. ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-custom-placeholder-base

---

kind: Service
apiVersion: v1
metadata:
  name: pingdirectory-admin
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pingdirectory-admin.amehrotra-primary.ping-demo.com
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    $patch: replace

---