#Cloudwatch related values
cloudwatch:
  enabled : "${CLOUDWATCH_ENABLED}"
  namespace: "amazon-cloudwatch"
#The IRSA role ARN to be used for the CWAgent serviceAccount, for the customer environment
  irsaCwAgentAnnotationKeyValue: "eks.amazonaws.com/role-arn: arn:aws:iam::705370621539:role/amehrotra-primary-irsa-cloudwatch"
  image:
    repository: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/amazon/cloudwatch-agent
    tag: 1.300026.3b189

  resources:
    limits:
      cpu:  200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi
